# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e420d0921cab7cd70451c41d597581b82f06ea4199afec40f1059d29e9b9ea58f365ba9bf9fb11b21c2b6fb87da0d787bbbecd8fecc6787f2d1c8368d31b88ff

test:
  secret_key_base: 4bc3bed6e625c0d25751cac6deb83f460eec3362e0e1d4deeb9be7b6277e305879d3c1ea4077512bc2575e6e59bafdb339d97c0cbf3748b07c455fb403e29896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
